package com.wutsi.application.shell.endpoint

object Page {
    const val HOME = "page.home"
    const val QR_CODE = "page.qr-code"
    const val SETTINGS = "page.settings"
    const val SETTINGS_ABOUT = "page.settings.about"
    const val SETTINGS_ACCOUNT = "page.settings.account"
    const val SETTINGS_ACCOUNT_LINK_MOBILE = "page.settings.account.link.mobile"
    const val SETTINGS_ACCOUNT_LINK_SUCCESS = "page.settings.account.link.success"
    const val SETTINGS_ACCOUNT_LINK_VERIFY = "page.settings.account.link.verify"
    const val SETTINGS_ACCOUNT_LINK_PIN = "page.settings.account.link.pin"
    const val SETTINGS_PICTURE = "page.settings.picture"
    const val SETTINGS_PROFILE = "page.settings.profile"
    const val SETTINGS_PROFILE_BIOGRAPHY = "page.settings.profile.biography"
    const val SETTINGS_PROFILE_CATEGORY = "page.settings.profile.category"
    const val SETTINGS_PROFILE_STREET = "page.settings.profile.street"
    const val SETTINGS_PROFILE_WEBSITE = "page.settings.profile.website"
    const val SETTINGS_PROFILE_WHATSAPP = "page.settings.profile.whatsapp"
    const val SETTINGS_SECURITY = "page.settings.security"
    const val SETTINGS_SECURITY_PIN = "page.settings.security.pin"
    const val SETTINGS_SECURITY_PIN_LOGIN = "page.settings.security.pin.login"
    const val SETTINGS_SECURITY_PIN_CONFIRM = "page.settings.security.pin.confirm"
    const val SETTINGS_BUSINESS = "page.settings.business"
    const val SCAN = "page.scan"
    const val SCAN_VIEWER = "page.scan.viewer"
    const val PROFILE = "page.profile"
}
